#ifndef MD_MDEF_TABLE_H
#define MD_MDEF_TABLE_H

/*
    ECMA-335 4th Edition Section 22
    Table Field Indexes
 
    These are the actual index of each
    field in the row for each table denoted.
 
    Although, each field has a certain size
    and most index type fields can actually
    vary in size from one module to the next.
 
    This normally serves as a constant to pass
    to the actual helper function which can
    access fields in a specified table and row.
 
    So now you have a textual name to reference
    instead of having to remember arbitray index.
*/
#define CLR20_TASSEMBLY_HASHALGID       0
#define CLR20_TASSEMBLY_VERMAJOR        1
#define CLR20_TASSEMBLY_VERMINOR        2
#define CLR20_TASSEMBLY_BUILDNUM        3
#define CLR20_TASSEMBLY_REVISION        4
#define CLR20_TASSEMBLY_PUBLICKEY       5
#define CLR20_TASSEMBLY_NAME            6
#define CLR20_TASSEMBLY_CULTURE         7
#define CLR20_TASSEMBLYOS_OSPLATFORMID      0
#define CLR20_TASSEMBLYOS_OSMAJORVERSION    1
#define CLR20_TASSEMBLYOS_OSMINORVERSION    2
#define CLR20_TASSEMBLYPROC_PROCESSOR       0
#define CLR20_TASSEMBLYREF_VERMAJOR     0
#define CLR20_TASSEMBLYREF_VERMINOR     1
#define CLR20_TASSEMBLYREF_BUILDNUM     2
#define CLR20_TASSEMBLYREF_REVISION     3
#define CLR20_TASSEMBLYREFOS_OSPLATFORMID   0
#define CLR20_TASSEMBLYREFOS_OSVERMAJOR     1
#define CLR20_TASSEMBLYREFOS_OSVERMINOR     2
#define CLR20_TASSEMBLYREFOS_ASSEMBLYREF    3
#define CLR20_TASSEMBLYREFPROC_PROCESSOR    0
#define CLR20_TASSEMBLYREFPROC_ASSEMBLYREF  1
#define CLR20_TCLASSLAYOUT_PACKINGSIZE      0
#define CLR20_TCLASSLAYOUT_CLASSSIZE        1
#define CLR20_TCLASSLAYOUT_PARENT       2
#define CLR20_TCONSTANT_TYPE            0
#define CLR20_TCONSTANT_PARENT          1
#define CLR20_TCONSTANT_VALUE           2
#define CLR20_TCUSTOMATTRI_PARENT       0
#define CLR20_TCUSTOMATTRI_TYPE         1
#define CLR20_TCUSTOMATTRI_VALUE        2
#define CLR20_TDECLSECURITY_ACTION      0
#define CLR20_TDECLSECURITY_PARENT      1
#define CLR20_TDECLSECURITY_PERMISSIONSET   2
#define CLR20_TEVENTMAP_PARENT          0
#define CLR20_TEVENTMAP_EVENTLIST       1
#define CLR20_TEXPORTEDTYPE_FLAGS       0
#define CLR20_TEXPORTEDTYPE_TYPEDEFID       1
#define CLR20_TEXPORTEDTYPE_TYPENAME        2
#define CLR20_TEXPORTEDTYPE_TYPENAMESPACE   3
#define CLR20_TEXPORTEDTYPE_IMPLEMENTATION  4
#define CLR20_TFIELD_FLAGS          0
#define CLR20_TFIELD_NAME           1
#define CLR20_TFIELD_SIGNATURE          2
#define CLR20_TFIELDLAYOUT_OFFSET       0
#define CLR20_TFIELDLAYOUT_FIELD        1
#define CLR20_TFIELDMARSHAL_PARENT      0
#define CLR20_TFIELDMARSHAL_NATIVETYPE      1
#define CLR20_TFIELDRVA_RVA         0
#define CLR20_TFIELDRVA_FIELD           1
#define CLR20_TFILE_FLAGS           0
#define CLR20_TFILE_NAME            1
#define CLR20_TFILE_HASHVALUE           2
#define CLR20_TGENERICPARAM_NUMBER      0
#define CLR20_TGENERICPARAM_FLAGS       1
#define CLR20_TGENERICPARAM_OWNER       2
#define CLR20_TGENERICPARAM_NAME        3
#define CLR20_TGENERICPARAMCONST_OWNER      0
#define CLR20_TGENERICPARAMCONST_CONSTRAINT 1
#define CLR20_TIMPLMAP_MAPPINGFLAGS     0
#define CLR20_TIMPLMAP_MEMBERFORWARDED      1
#define CLR20_TIMPLMAP_IMPORTNAME       2
#define CLR20_TIMPLMAP_IMPORTSCOPE      3
#define CLR20_TIFACEIMPL_CLASS          0
#define CLR20_TIFACEIMPL_INTERFACE      1
#define CLR20_TMANIFESTRES_OFFSET       0
#define CLR20_TMANIFESTRES_FLAGS        1
#define CLR20_TMANIFESTRES_NAME         2
#define CLR20_TMANIFESTRES_IMPLEMENTATION   3
#define CLR20_TMEMBERREF_CLASS          0
#define CLR20_TMEMBERREF_NAME           1
#define CLR20_TMEMBERREF_SIGNATURE      2
#define CLR20_TMETHODDEF_RVA            0
#define CLR20_TMETHODDEF_IMPLFLAGS      1
#define CLR20_TMETHODDEF_FLAGS          2
#define CLR20_TMETHODDEF_NAME           3
#define CLR20_TMETHODDEF_SIGNATURE      4
#define CLR20_TMETHODDEF_PARAMLIST      5
#define CLR20_TMETHODIMPL_CLASS         0
#define CLR20_TMETHODIMPL_METHODBODY        1
#define CLR20_TMETHODIMPL_METHODDECLARATION 2
#define CLR20_TMETHODSEMAN_SEMANTICS        0
#define CLR20_TMETHODSEMAN_METHOD       1
#define CLR20_TMETHODSEMAN_ASSOCIATION      2
#define CLR20_TMETHODSPEC_METHOD        0
#define CLR20_TMETHODSPEC_INSTANTIATION     1
#define CLR20_TMODULE_GENERATION        0
#define CLR20_TMODULE_NAME          1
#define CLR20_TMODULE_MVID          2
#define CLR20_TMODULE_ENCID         3
#define CLR20_TMODULE_ENCBASEID         4
#define CLR20_TMODULEREF_NAME           0
#define CLR20_TNESTEDCLASS_NESTEDCLASS      0
#define CLR20_TNESTEDCLASS_ENCLOSINGCLASS   1
#define CLR20_TPARAM_FLAGS          0
#define CLR20_TPARAM_SEQUENCE           1
#define CLR20_TPARAM_NAME           2
#define CLR20_TPROPERTY_FLAGS           0
#define CLR20_TPROPERTY_NAME            1
#define CLR20_TPROPERTY_TYPE            2
#define CLR20_TPROPERTYMAP_PARENT       0
#define CLR20_TPROPERTYMAP_PROPERTYLIST     1
#define CLR20_TSTANDALONGSIG_SIGNATURE      0
#define CLR20_TTYPEDEF_FLAGS            0
#define CLR20_TTYPEDEF_TYPENAME         1
#define CLR20_TTYPEDEF_TYPENAMESPACE        2
#define CLR20_TTYPEDEF_EXTENDS          3
#define CLR20_TTYPEDEF_FIELDLIST        4
#define CLR20_TTYPEDEF_METHODLIST       5
#define CLR20_TTYPEREF_RESOLUTIONSCOPE      0
#define CLR20_TTYPEREF_TYPENAME         1
#define CLR20_TTYPEREF_TYPENAMESPACE        2
#define CLR20_TTYPESPEC_SIGNATURE       0

#endif